BaseCap-Analytics/CloudAbstractions

src/CloudAbstractions.csproj
Updating nuget package versions
=> Updating package versions

src/Abstractions/ITableStorage.cs, src/Implementations/AzureTableStorage.cs
Adding batching to Table Inserts
=> Adding batching to Table inserts

src/Abstractions/IQueue.cs, src/Implementations/AzureQueueStorage.cs, src/Implementations/Secure/AzureEncryptedQueueStorage.cs
Fixing bug where Queue Visibility was mistaken for Timeout and therefore causing duplicate parsing
=> Fixing bug where Queue Visibility was mistaken for Timeout

src/Abstractions/IEventStreamReader.cs, src/Implementations/AzureEventHubReader.cs, src/Implementations/Secure/AzureEncryptedEventHubReader.cs
Removing wait times and timeouts from event stream reader
=> Removing event stream wait times

src/Implementations/AzureEventHubReader.cs
Fixing offset mistake where we thought it was a key not a property
=> Fixing offset mistake in event data

src/Abstractions/ISecretProvider.cs, src/Implementations/AzureKeyVault.cs
Adding capability to create/update secrets
=> Adding capability to create/update secrets

src/CloudAbstractions.csproj, src/Implementations/AzureStorageAccount.cs
Fixing package version and removing unnecessary function
=> Fixing package version

src/Implementations/AzureTableStorage.cs
Adding retry policy to Table storage
=> Adding retry policy to Table storage

src/Implementations/AzureTableStorage.cs
Making storage queries have a linear timeout
=> Making Storage timeouts linear

src/Abstractions/IEventStreamReader.cs, src/Abstractions/IEventStreamWriter.cs, src/Implementations/AzureEventHubReader.cs, src/Implementations/AzureEventHubWriter.cs, src/Implementations/Secure/AzureEncryptedEventHubReader.cs
Adding CloseAsync to EventStream Reader/Writer
=> Adding CloseAsync to EventStream Reader/Writer

src/Abstractions/CloudJob.cs, src/Abstractions/CloudJobTask.cs, src/Abstractions/IJobScheduler.cs, src/CloudAbstractions.csproj, src/Implementations/AzureBatch.cs
Adding basic support for Azure Batch
=> Adding Batch Job

src/Implementations/AzureBatch.cs
Fixing bug to add environment variables to the task
=> Fixing bug to add environment variables to the task

src/Abstractions/IJobScheduler.cs, src/Implementations/AzureBatch.cs
Adding ability to target Job Pool dynamically
=> Adding ability to target Job Pool dynamically

src/Implementations/AzureBatch.cs
Moving batch to Shared Key credentials
=> Moving batch to Shared Key credentials

src/Abstractions/IJobScheduler.cs, src/Implementations/AzureBatch.cs
Adding ability to re-size batch pools
=> Adding ability to re-size batch pools

src/Implementations/AzureBlobStorage.cs
Adding SaS token constructor to Storage Accounts
=> Adding SaS token constructor to Storage Accounts

src/Abstractions/CloudScheduledJob.cs, src/Abstractions/IJobScheduler.cs, src/Implementations/AzureBatch.cs
Adding ability to schedule jobs in Batch
=> Adding ability to schedule jobs in Batch

src/Abstractions/IJobScheduler.cs, src/Implementations/AzureBatch.cs
Adding the ability to add a Start Task to Batch Pools
=> Adding ability to add Start Task to Batch Pools

src/Implementations/AzureBlobStorage.cs
Fixing issue where Blob Containers would not be created from SAS tokens
=> Fixing Blob Container from SAS token issue

src/Implementations/AzureBatch.cs
Fixing problem where Batch Application Packages would not be installed correctly
=> Fixing batch application package installation

src/Abstractions/BlobItem.cs, src/Abstractions/IBlobStorage.cs, src/CloudAbstractions.csproj, src/Implementations/AzureBlobStorage.cs
Adding ability to enumerate Blobs as well as Directories
=> Adding Directory and Blob enumeration

src/Abstractions/BlobItem.cs
Adding full Blob URI to BlobItem
=> Adding full blob URI to BlobItem

src/Abstractions/IQueue.cs, src/Implementations/AzureQueueStorage.cs
Adding additional PushObjectAsMessage call that allows for initial message delivery delay
=> Adding additional PushObjectAsMessage call

src/Abstractions/ITableStorage.cs, src/Implementations/AzureTableStorage.cs
Adding Count function to Table Storage
=> Adding Count function to Tables

src/Abstractions/ITableStorage.cs, src/Implementations/AzureTableStorage.cs
Adding ability to readonly iterate over a table's rows
=> Adding ability to readonly traverse a table

src/Abstractions/ITableStorage.cs, src/Implementations/AzureTableStorage.cs
Adding CancellationToken to Table Traversal
=> Adding CancellationToken to Table Traversal

src/Implementations/AppInsightsLogger.cs
Fixing AppInsights logger namespace
=> Fixing AppInsights logger namespace

src/Abstractions/IBlobStorage.cs, src/Abstractions/ITableStorage.cs, src/Implementations/AzureBlobStorage.cs, src/Implementations/AzureTableStorage.cs
Adding code to delete old blobs and old table entities
=> Add ability to delete old blobs and table entities

src/Abstractions/ITableStorage.cs, src/Implementations/AzureTableStorage.cs
Adds function to get all table names
=> Add function to iterate over all table names

src/Implementations/AzureBlobStorage.cs
Fixing broke blob continuation tokens
=> Fixing broken continuation token

src/Abstractions/ICache.cs, src/CloudAbstractions.csproj, src/Implementations/AzureRedisCache.cs
Adding abstraction and implementation for Redis caching
=> Adding abstraction and implementation for Redis

src/Abstractions/ICache.cs, src/Implementations/AzureRedisCache.cs
Adding expiry add cache object function
=> Adding expiry add for redis

src/Abstractions/ICache.cs, src/Implementations/AzureRedisCache.cs, src/Implementations/Secure/AzureEncryptedRedisCache.cs
- Adding auto-encrypted Redis
- Adding support for Lists in Redis
=> Adding encrypted Redis

src/Abstractions/ICache.cs, src/Implementations/AzureRedisCache.cs, src/Implementations/Secure/AzureEncryptedRedisCache.cs
Updating Redis code to return more useful info
=> Updating Redis

src/Implementations/AzureRedisCache.cs
GetList call was not returning correct data; fixing it
=> Fixing redis GetList call

src/Abstractions/IQueue.cs, src/Abstractions/IStorageAccount.cs, src/Abstractions/QueueMessage.cs, src/CloudAbstractions.csproj, src/Implementations/AzureQueueStorage.cs, src/Implementations/AzureStorageAccount.cs, src/Implementations/Secure/AzureEncryptedQueueStorage.cs, src/Implementations/Secure/AzureEncryptedStorageAccount.cs
Converting Queues over to Service Bus
=> Converting Queues over to Service Bus

src/Abstractions/IQueue.cs, src/Implementations/AzureQueueStorage.cs
Updating IQueue to take a configurable number of readers
=> Updating SB Queue

src/Implementations/Secure/AzureEncryptedQueueStorage.cs
Fixen broken seamless queue decryption
=> Fixing broken queue decryption

src/CloudAbstractions.csproj, src/Implementations/AppInsightsLogger.cs
=> Version bump

src/Implementations/AzureEventHubWriter.cs
=> Fixing memory leak

src/Implementations/AzureQueueStorage.cs
Fixing bug where Queue Options weren't being used
=> Fixing Queue Options bug

src/Abstractions/ILogger.cs, src/Implementations/AppInsightsLogger.cs, src/Implementations/AzureEventHubReader.cs, src/Implementations/AzureQueueStorage.cs, src/Implementations/ConsoleLogger.cs, src/Implementations/Secure/AzureEncryptedQueueStorage.cs
Hardening the Queue Implementation
=> Hardening the Queue implementation

src/CloudAbstractions.csproj, src/Implementations/AzureQueueStorage.cs
Reverting to netstandard2.0 and fixing bug in queue ctor
=> Reverting to netstandard2.0 and fixing bug in queue ctor

src/Implementations/AzureRedisCache.cs, src/Implementations/Secure/AzureEncryptedRedisCache.cs
Fixing redis implementation for local
=> Fixing Redis for local

src/Implementations/AzureStorageAccount.cs, src/Implementations/LocalTesting/LocalRedisEventReader.cs, src/Implementations/LocalTesting/LocalRedisEventWriter.cs, src/Implementations/LocalTesting/LocalRedisQueue.cs
Adding local versions for Event Hub and Service Bus by utilizing Redis Pub/Sub
=> Adding local versions for Event Hub and Service Bus

src/Abstractions/IQueue.cs, src/Implementations/AzureQueueStorage.cs, src/Implementations/LocalTesting/LocalRedisEventReader.cs, src/Implementations/LocalTesting/LocalRedisEventWriter.cs, src/Implementations/LocalTesting/LocalRedisQueue.cs
- Adding Close on IQueue to clean up nicely
- Fixing Redis testing namespaces
=> Adding Close on IQueue and fixing namespaces

src/Implementations/AzureQueueStorage.cs, src/Implementations/AzureRedisCache.cs, src/Implementations/Secure/AzureEncryptedRedisCache.cs
Hardening the redis implementation with timeouts and recreating connections
=> Hardening redis implementation

src/Implementations/AzureQueueStorage.cs, src/Implementations/Secure/AzureEncryptedQueueStorage.cs
Fixing implementation of Queue using limitations in StackExchange.Redis
=> Fixing StachExchange Redis queue

src/Abstractions/INotificationReceiver.cs, src/Implementations/Redis/RedisPubSubReceiver.cs
Fixing Pub/Sub Receiver handler to take in an awaitable function
=> Fixing Pub/Sub Receiver Handler Func

.config/dotnet-tools.json, src/Abstractions/INotificationReceiver.cs, src/Abstractions/INotificationSender.cs, src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs
Updating Queue to use Pub/Sub as a shoulder tap in order to remove the Polling
=> Updating Queue from Polling to Blocking

src/Abstractions/ICache.cs, src/Abstractions/IHyperLogLog.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs
Adding initial HashSet and HyperLogLog support to Redis abstraction
=> Adding initial HashSet and HyperLogLog support to Redis abstraction

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding ability to create HyperLogLog from Redis Cache object
=> Adding ability to create HyperLogLog from Redis Cache object

src/Abstractions/ICache.cs, src/Abstractions/IHyperLogLog.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs
- Adding function to increment redis hash field by a specified value
- Fixing HyperLogLog Delete name to be Async
=> Fixing redis cache and hyperloglog implementation

src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs, src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs
Adding ability to specify multiple Redis Endpoints in the Redis implementations
=> Adding multiple endpoints option for redis

src/Abstractions/EventMessage.cs, src/Abstractions/IEventStreamReader.cs, src/Abstractions/IEventStreamWriter.cs, src/Implementations/Azure/AzureEventHubReader.cs, src/Implementations/Azure/AzureEventHubWriter.cs, src/Implementations/Azure/Secure/AzureEncryptedEventHubReader.cs, src/Implementations/Azure/Secure/AzureEncryptedEventHubWriter.cs, src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubReceiver.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubSender.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamSender.cs
Adding plaintext and encrypted access to Redis Streams
=> Adding implementation for Redis Streams

src/Abstractions/IEventStreamReader.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
Fixing issue where Redis Stream would deliver 1 message at a time rather than in batches
=> Fixing redis stream implementation

src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs
Adding helpers to ensure that streams and stream consumer groups are created before attempting to use
=> Adding stream helpers

src/Implementations/Redis/RedisQueueStorage.cs
Fixing queue implementation to not wait for shoulder taps if there is more data in the queue
=> Fixing queue implementation

src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
Fixing bug where we were attempting to change a collection while enumerating over it
=> Fixing collection change bug

src/Abstractions/EventMessage.cs
Fixing bug where we would leak Redis details through the event message
=> Fixing EventMessage creation bug

src/Implementations/Redis/RedisBase.cs
Adding constant max length to a redis stream
=> Adding max length to a redis stream

.build_definitions/build-and-save.yaml, .build_definitions/build.yaml, .build_definitions/ci.yaml, .build_definitions/pr.yaml, .build_definitions/publish-nuget.yaml
Adding DevOps build definitions files
=> Adding build definitions

.build_definitions/publish-nuget.yml
Fixing publish YAML file to correctly publish
=> Fixing publish YAML

.build_definitions/ci.yml, .build_definitions/pr.yml, .build_definitions/publish-nuget.yml, README.md, src/CloudAbstractions.csproj
Fixing YML to use free, hosted CI machines and Readme file to point to CI badge
=> Fixing YML and Readme

.build_definitions/publish-nuget.yml, src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamSender.cs, src/Implementations/Redis/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubSender.cs, src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamSender.cs
Adding JSON serialization settings to Redis implementations
=> Adding serialization settings to Redis

src/CloudAbstractions.csproj, src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamSender.cs, src/Implementations/Redis/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubSender.cs, src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamSender.cs
Converting from Newtonsoft JSON to System.Text.Json in Redis implementations
=> Converting from Newtonsoft JSON to System.Text.Json

src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubReceiver.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
Adding decryption hardening for cases where unencrypted data is received when encrypted data is expected
=> Adding decryption hardening for incorrect data cases

src/CloudAbstractions.csproj, src/Implementations/Redis/RedisBase.cs
Reverting back to newtonsoft JSON since System.Text.json has limitations around loop references
=> Reverting back to Newtonsoft

src/Implementations/Redis/RedisBase.cs
Adding reference tracking to JSON serialization and deserialization
=> Adding Reference Tracking to JSON options

src/Implementations/Redis/RedisCache.cs
Fixing bug where HashGetFieldValue would return incorrect results
=> Fixing Redis HashGetFieldValue

src/Abstractions/IEventStreamReader.cs, src/Implementations/Redis/RedisStreamReader.cs
Adding MaxCount parameter to Stream Read interface
=> Adding max count to stream read

src/Abstractions/EventMessage.cs, src/Abstractions/IEventStreamWriter.cs, src/Implementations/Azure/AzureEventHubWriter.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
Fixing bug where redis stream entries with multiple values were not processed correctly
=> Fixing multi-item stream entries

src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisStreamReader.cs
Adding non-consumer-group redis stream reading
=> Adding non-consumer-group redis stream reading

src/Implementations/Redis/RedisStreamReader.cs
Fixing bug where redis implementation didn't allow for null passwords
=> Fixing password check bug

src/Implementations/Redis/RedisStreamReader.cs
Fixing missed password check removal
=> Fixing missed password check removal

src/Implementations/Redis/RedisStreamReader.cs
Fixing xread to read from the most recent message using message IDs
=> Fixing redis XREAD call to fit spec

src/Implementations/Redis/RedisStreamReader.cs
Adding StreamPosition check for XREAD*
=> Adding StreamPosition check for XREAD*

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding basic redis sorted set functionality
=> Adding basic sorted set functionality

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding fire-and-forget flag to redis
=> Adding fire-and-forget flag to redis

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding redis API call to set key expiry time
=> Adding call to expire keys

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding Score to output of SortedSet Get function
=> Adding Score to output of SortedSet Get function

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding HashGetAll to retrieve a lookup of all hash field names and their values
=> Adding HashGetAll to retrieve hash keys and values

src/Implementations/Redis/RedisCache.cs
Fixing redis key expiry to correctly set the DateTime of the expiry
=> Fixing redis Key Expiry

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs
Adding ability to atomically setting a flag in a hash field of redis
=> Adding atomic flag set in redis

.config/dotnet-tools.json, src/Abstractions/IDocumentDb.cs, src/CloudAbstractions.csproj, src/Implementations/MongoDb/MongoDb.cs
Adding initial support for DocumentDBs like MongoDB
=> Adding initial support for MongoDB

src/Abstractions/IDocumentDb.cs, src/Abstractions/IDocumentDbCursor.cs, src/Implementations/MongoDb/MongoCursor.cs, src/Implementations/MongoDb/MongoDb.cs
Adding Count function to be able to count the number of documents in a result set
=> Adding Count function to DocumentDb

src/Abstractions/IDocumentDb.cs, src/Implementations/MongoDb/MongoDb.cs
Adding pagination Mongo APIs and overhauling search and filter expressions
=> Adding pagination Mongo APIs and overhauling search and filter expressions

src/Abstractions/IDocumentDb.cs, src/Implementations/MongoDb/MongoDb.cs
Fixing expiry index for mongo db to make it a LINQ expression
=> Fixing expiry index for mongo db

src/Implementations/MongoDb/MongoDb.cs
Adding local, auth-less MongoDb constructor
=> Adding local, auth-less MongoDb constructor

src/Abstractions/IEmailSender.cs, src/CloudAbstractions.csproj, src/Implementations/SendGrid/SendGridEmailSender.cs
Adding Email sending abstraction and implementation via SendGrid
=> Adding SendGrid abstraction and implementation

src/Implementations/SendGrid/SendGridEmailSender.cs
Fixing SendGrid timeouts since they had invalid runtime values previously
=> Fixing SendGrid timeouts

src/Implementations/MongoDb/MongoDb.cs
Fixing mongo login to always login to the admin DB
=> Fixing mongo login

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Changing SetHashFieldNx to SetHashField
=> Moving SetHashFieldNx to SetHashField

src/Abstractions/BlobItem.cs, src/Abstractions/IStorageAccount.cs, src/CloudAbstractions.csproj, src/Implementations/Azure/AzureStorageAccount.cs
Adding ability to list containers in an Azure Storage Account
=> Adding container listing to Azure Storage Account

.github/workflows/ci-cd.yml
Trying to fix nuget push to GitHub
=> Trying to fix nuget push to GitHub

.github/workflows/ci-cd.yml
NuGet seems broken on Ubuntu so try using Windows
=> Use Windows machine for Ci/CD for Nuget to work

.github/workflows/ci-cd.yml
Switching back to Ubuntu and using manual nuget push
=> Switching back to Ubuntu and using manual nuget push

.github/workflows/ci-cd.yml
=> Fixing CI/CD relative path

.github/workflows/ci-cd.yml, src/Implementations/Azure/AzureStorageAccount.cs
Fixing broken ListContainers function that would never return
=> Fixing the Azure Blob ListContainers function

.github/workflows/ci-cd.yml
Trying to fix nuget push in CD
=> Trying to fix nuget push in CD

.github/workflows/ci-cd.yml
=> Fixing NuGet push command

.github/workflows/ci-cd.yml
Moving from GitHub packages back to MyGet
=> Moving from GitHub packages back to MyGet

.github/workflows/ci-cd.yml
Switching back to dotnet cli instead of nuget.exe
=> Switching back to dotnet cli instead of nuget.exe

.github/workflows/ci-cd.yml, .github/workflows/pr.yml, src/Abstractions/ICache.cs, src/CloudAbstractions.csproj, src/Implementations/Redis/RedisCache.cs
Adding Remove calls to redis types to allow deleting of specific redis values without deleting the whole key
=> Adding Remove* calls to redis types

src/Abstractions/IQueueListener.cs, src/Abstractions/IQueueListenerTarget.cs, src/Abstractions/IQueueSender.cs, src/Abstractions/QueueMessage.cs, src/CloudAbstractions.csproj, src/Implementations/RabbitMq/RabbitQueueListener.cs, src/Implementations/RabbitMq/RabbitQueueManager.cs, src/Implementations/RabbitMq/RabbitQueueSender.cs, src/Implementations/RabbitMq/Secure/RabbitSecureQueueListener.cs, src/Implementations/RabbitMq/Secure/RabbitSecureQueueSender.cs, src/Implementations/Redis/RedisQueueStorage.cs
Adding support for RabbitMQ for queuing
=> Adding RabbitMQ support for queues

src/Implementations/RabbitMq/RabbitQueueSender.cs
Fixing additional argument exception around RabbitMQ exchange
=> Fixing incorrect argument exception

src/Abstractions/IQueueSender.cs, src/Implementations/RabbitMq/RabbitQueueListener.cs, src/Implementations/RabbitMq/RabbitQueueSender.cs, src/Implementations/RabbitMq/Secure/RabbitSecureQueueListener.cs, src/Implementations/RabbitMq/Secure/RabbitSecureQueueSender.cs
Fixing bug where secure queue listener wouldn't decrypt messages
=> Fixing broken secure queue listener

src/Abstractions/IQueueBatchListenerTarget.cs, src/Abstractions/IQueueListener.cs, src/Abstractions/QueueMessage.cs, src/Implementations/RabbitMq/RabbitQueueListener.cs, src/Implementations/RabbitMq/RabbitQueueManager.cs, src/Implementations/RabbitMq/Secure/RabbitSecureQueueListener.cs
Adding ability to read batches of messages from RabbitMQ
=> Adding batch RabbitMQ listener

src/Abstractions/IQueueSender.cs, src/Implementations/RabbitMq/RabbitQueueSender.cs, src/Implementations/RabbitMq/Secure/RabbitSecureQueueSender.cs
Adding ability to bulk send messages to RabbitMQ
=> Adding bulk RabbitMQ sending

src/Abstractions/IQueueBatchListenerTarget.cs, src/Abstractions/IQueueListener.cs, src/Abstractions/IQueueListenerTarget.cs, src/Implementations/RabbitMq/RabbitQueueListener.cs
Allowing individual messages to be ack/nack'd in order to prevent a single back message from breaking a whole batch
=> Allowing individual messages to be ack/nack'd

src/Implementations/RabbitMq/RabbitQueueListener.cs
Simplifying the Rabbit Queue Listener to remove so much thread synchronization
=> Simplifying Rabbit listener

src/Implementations/RabbitMq/RabbitQueueListener.cs
- Adding speed up to event listener to fire batch to listener when its full
=> Adding perf improvement to speed up rabbit listener

src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs, src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs
- Fixing redis connection to adhere to connection recommendations https://stackexchange.github.io/StackExchange.Redis/Basics.html
=> Fixing redis connection to be more hardened

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding ability to get list element by index
=> Adding Redis List IndexOf support

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding ability to use redis sorted sets like a numeric-based hash table
=> Adding use of redis sorted set for numeric lookup

src/CloudAbstractions.csproj
Updating NuGet package versions
=> Updating NuGet package versions

src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs, src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs, src/Implementations/Redis/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubReceiver.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubSender.cs, src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamSender.cs
Changing Redis constructors to use Connection Strings
=> Changing Redis constructors to use Connection Strings

src/Abstractions/IEventStreamReader.cs, src/Abstractions/IEventStreamWriter.cs, src/Abstractions/IHyperLogLog.cs, src/Abstractions/INotificationReceiver.cs, src/Abstractions/INotificationSender.cs, src/Abstractions/IQueue.cs, src/Abstractions/IQueueListener.cs, src/Abstractions/IQueueSender.cs, src/CloudAbstractions.csproj, src/Implementations/Azure/AzureEventHubWriter.cs
Fixing missing disposable interface declarations on classes needing it
=> Fixing missing disposable declarations

src/Abstractions/IBlobStorage.cs, src/Implementations/Azure/AzureBlobStorage.cs
Adding helper function to allow moving blobs in azure
=> Adding helper function to allow moving blobs in azure

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs
Adding retries to Redis commands
=> Adding retry logic to Redis commands

src/CloudAbstractions.csproj, src/Implementations/Redis/RedisBase.cs
=> Bumping redis client version

src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs
Fixing reconnect logic to rebuild DB object on reconnect
=> Fixing reconnect logic to rebuild DB object on reconnect

src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs, src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs, src/Implementations/Redis/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubReceiver.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubSender.cs, src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamSender.cs
Switching redis constructors over to use multiple endpoints
=> Switching redis constructors over to use multiple endpoints

src/Abstractions/QueueMessage.cs, src/CloudAbstractions.csproj, src/Implementations/RabbitMq/RabbitQueueListener.cs, src/Implementations/RabbitMq/Secure/RabbitSecureQueueListener.cs
=> Adding support for Spans

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding call to allow removing specific entries from a sorted set
=> Adding Remove call for Redis Sorted Set

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding function for Sorted Set Add that will only add an item if the sorted set exists
=> Adding check for Redis Sorted Set Add

src/Abstractions/ICache.cs, src/Implementations/Redis/RedisCache.cs
Adding call to add to hash set only if the key exists
=> Adding HashSetAdd with Exists condition

src/CloudAbstractions.csproj
=> Updating package references

src/CloudAbstractions.csproj
=> Bumping security package

src/Abstractions/INotificationReceiver.cs, src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisPubSubReceiver.cs
=> Adding blocking pubsub reads

src/CloudAbstractions.csproj
=> Updating NuGet packages

src/CloudAbstractions.csproj, src/Implementations/Redis/RedisBase.cs, src/Implementations/Redis/RedisCache.cs, src/Implementations/Redis/RedisHyperLogLog.cs, src/Implementations/Redis/RedisPubSubReceiver.cs, src/Implementations/Redis/RedisPubSubSender.cs, src/Implementations/Redis/RedisQueueStorage.cs, src/Implementations/Redis/RedisStreamReader.cs, src/Implementations/Redis/RedisStreamSender.cs, src/Implementations/Redis/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubReceiver.cs, src/Implementations/Redis/Secure/EncryptedRedisPubSubSender.cs, src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs, src/Implementations/Redis/Secure/EncryptedRedisStreamSender.cs
=> Adding UseSsl flag for Redis

src/Abstractions/IStorageAccount.cs, src/CloudAbstractions.csproj, src/Implementations/Azure/AzureStorageAccount.cs
Adding un-abstracted support for Azure Table Storage
=> Adding un-abstracted support for Azure Table Storage

src/Implementations/Azure/AzureStorageAccount.cs
Fixing bug where table storage would not auth correctly
=> Fixing bug with table storage access

src/Abstractions/IRedisDatabase.cs, src/Implementations/Redis/Database/RedisDatabase.Keys.cs
Adding SET and GET commands for Redis
=> Adding SET and GET commands for Redis

src/Abstractions/Legacy/EventMessage.cs, src/Abstractions/Legacy/ICache.cs, src/Abstractions/Legacy/ICheckpointer.cs, src/Abstractions/Legacy/IEventStreamHub.cs, src/Abstractions/Legacy/IEventStreamReader.cs, src/Abstractions/Legacy/IEventStreamWriter.cs, src/Implementations/Azure/Legacy/AzureEventHub.cs, src/Implementations/Azure/Legacy/AzureEventHubReader.cs, src/Implementations/Azure/Legacy/AzureEventHubWriter.cs, src/Implementations/Azure/Legacy/Secure/AzureEncryptedEventHubReader.cs, src/Implementations/Azure/Legacy/Secure/AzureEncryptedEventHubWriter.cs, src/Implementations/GenericLegacy/EventCheckpointer.cs, src/Implementations/Redis/Legacy/RedisBase.cs, src/Implementations/Redis/Legacy/RedisCache.cs, src/Implementations/Redis/Legacy/RedisHyperLogLog.cs, src/Implementations/Redis/Legacy/RedisPubSubReciever.cs, src/Implementations/Redis/Legacy/RedisPubSubSender.cs, src/Implementations/Redis/Legacy/RedisQueueStorage.cs, src/Implementations/Redis/Legacy/RedisStreamReader.cs, src/Implementations/Redis/Legacy/RedisStreamSender.cs, src/Implementations/Redis/Legacy/Secure/EncryptedRedisCache.cs, src/Implementations/Redis/Legacy/Secure/EncryptedRedisPubSubReceiver.cs, src/Implementations/Redis/Legacy/Secure/EncryptedRedisPubSubSender.cs, src/Implementations/Redis/Legacy/Secure/EncryptedRedisQueueStorage.cs, src/Implementations/Redis/Legacy/Secure/EncryptedRedisStreamReader.cs, src/Implementations/Redis/Legacy/Secure/EncryptedRedisStreamSender.cs
Reimplemented Jon's code in "Legacy" folders but original namespace.
=> Reimplement legacy code

.github/workflows/ci-cd.yml
=> fixed ci\cd pipeline
