- src/CloudAbstractions.csproj
- src/Implementations/AzureEventHubReader.cs
Filtering out duplicate Events from an Event Stream using a 60 second timeout for each event ID
> Adding duplicate event filtering from Event Streams

- src/Abstractions/IJobScheduler.cs
- src/Implementations/AzureBatch.cs
Fixing function name for Pool Start Task; it had "Reboot" in it when the function did not cause a reboot
> Fixing function name for Pool Start Task

- src/Abstractions/BlobItem.cs
Fixing BlobItem Name when created from a directory; before, Name would actually be the full relative path since GetDirectoryName only formatted the path correctly. Now, we format the name and then retrieve the folder name
> Fixing BlobItem Directory Name

- src/Implementations/AzureRedisCache.cs
Fixing broken Redis timeout where `Milliseconds` was used instead of `TotalMilliseconds`
> Fixing broken Redis timeout

- src/Implementations/Azure/AppInsightsLogger.cs
Fixing App Insights logger constructor to use passed in Configuration instead of the deprecated `Active` singleton
> Fixing AppInsights logger constructor

- src/Abstractions/IHyperLogLog.cs
- src/Implementations/Redis/RedisHyperLogLog.cs
Fixing bug where the RedisHyperLogLog implementation did not have a Setup call and did not declare that it implements the IHyperLogLog interface
> Fixing interface bug on HyperLogLog

- src/Abstractions/ICache.cs
- src/Implementations/Redis/RedisCache.cs
Adding function DoesHashFieldExistAsync to check if a given field exists in the specified hashset
> Adding DoesHashFieldExistAsync function to RedisCache

- src/Abstractions/IQueue.cs
- src/Implementations/Azure/AzureQueueStorage.cs
- src/Implementations/Azure/Secure/AzureEncryptedQueueStorage.cs
- src/Implementations/Redis/RedisBase.cs
- src/Implementations/Redis/RedisCache.cs
- src/Implementations/Redis/RedisHyperLogLog.cs
- src/Implementations/Redis/RedisPubSubReceiver.cs
- src/Implementations/Redis/RedisPubSubSender.cs
- src/Implementations/Redis/RedisQueueStorage.cs
- src/Implementations/Redis/RedisStreamReader.cs
- src/Implementations/Redis/RedisStreamSender.cs
Fixing RedisBase intialization naming to not clash with implementing interfaces
> Fixing RedisBase intialization naming

- src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
Fixing bug where we sent the encrypted stream messages through instead of the decrypted ones
> Fixing quick bug in Encrypted Redis Stream

- src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
Fixing bug where we put the wrong ID in the decrypted stream result set
> Fixing bug in Secure Stream

- src/Implementations/Redis/RedisStreamSender.cs
Fixing bug where Stream Sender called into base directly instead of the virtual function
> Fixing serialization bug

- src/Implementations/Redis/RedisPubSubSender.cs
- src/Implementations/Redis/RedisQueueStorage.cs
- src/Implementations/Redis/RedisStreamSender.cs
Adding null and empty checks to all senders to ensure we don't add blank messages to cloud services
> Adding null checks for data senders

- src/Abstractions/IEventStreamWriter.cs
- src/Implementations/Azure/AzureEventHubWriter.cs
- src/Implementations/Redis/RedisStreamSender.cs
Fixing bug where the function call to add a single event to the stream would prevent the function taking in an enumerable from being called due to precedence of objects
> Fixing bug with ambiguous function call

- src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
Adding redis consumer-group-less stream reading in encrypted clients
> Adding redis consumer-group-less stream reading in encrypted clients

- src/Implementations/MongoDb/MongoDb.cs
Fixing MongoDb constructor to not take a port but instead an address with optional port in the address
> Fixing MongoDb constructor to not take a port

- src/Abstractions/ICache.cs
Fixing bug where ICache did not propagate implementations markings of being Disposable
> Fixing bug where ICache did not propagate IDisposable

- .github/workflows/ci-cd.yml
Fixing SetupDotnet version in YAML to use the latest 1.4 version for nuget pushing to work
> Fixing SetupDotnet version in YAML

- src/Abstractions/ICache.cs
- src/CloudAbstractions.csproj
- src/Implementations/Redis/RedisCache.cs
Adding Async Enumerable support to Redis class to deal with Redis Cursors and not needing to pull whole sets and hashes into memory at once
> Adding Async Enumerable support to Redis

- .github/workflows/ci-cd.yml
- .github/workflows/pr.yml
- src/CloudAbstractions.csproj
- src/Implementations/RabbitMq/RabbitQueueManager.cs
The Exchange variable isn't useful to us right now, so removing it for default implementation
> Fixing RabbitMQ exchange variable

- src/Implementations/RabbitMq/RabbitQueueSender.cs
Fixing bug where RabbitMQ bulk sending would send the whole enumerable as one object instead of as multiple messages with one object each
> Fixing bug where bulk sending would send as one object

- src/Abstractions/IQueueBatchListenerTarget.cs
- src/Abstractions/IQueueListenerTarget.cs
- src/Implementations/RabbitMq/RabbitQueueListener.cs
- src/Implementations/RabbitMq/RabbitQueueSender.cs
- Adding message TTL value of 12 hours per-message to Rabbit Messages
- Adding ACK and NACK support to allow message re-delivery
> Adding TTL values and NACK support to Rabbit

- src/Abstractions/IEmailSender.cs
- src/Implementations/Azure/AzureEventHub.cs
- src/Implementations/Azure/AzureEventHubReader.cs
- src/Implementations/Azure/Secure/AzureEncryptedEventHubReader.cs
- src/Implementations/Generic/EventCheckpointer.cs
- src/Implementations/Redis/RedisBase.cs
- src/Implementations/Redis/RedisCache.cs
- src/Implementations/Redis/RedisHyperLogLog.cs
- src/Implementations/Redis/RedisPubSubReceiver.cs
- src/Implementations/Redis/RedisPubSubSender.cs
- src/Implementations/Redis/RedisQueueStorage.cs
- src/Implementations/Redis/RedisStreamReader.cs
- src/Implementations/Redis/RedisStreamSender.cs
- src/Implementations/Redis/Secure/EncryptedRedisCache.cs
- src/Implementations/Redis/Secure/EncryptedRedisPubSubReceiver.cs
- src/Implementations/Redis/Secure/EncryptedRedisPubSubSender.cs
- src/Implementations/Redis/Secure/EncryptedRedisQueueStorage.cs
- src/Implementations/Redis/Secure/EncryptedRedisStreamReader.cs
- src/Implementations/Redis/Secure/EncryptedRedisStreamSender.cs
- src/Implementations/SendGrid/SendGridEmailSender.cs
Removing object-instance reference to Logger and using static logger instead for cleaner calls
> Removing references to Logger object

- src/Implementations/Redis/RedisBase.cs
Fixing bug where Redis password was not applied to the configuration object
> Fixing bug where Redis password was not applied

- src/Abstractions/INotificationReceiver.cs
- src/Implementations/Redis/RedisPubSubReceiver.cs
- src/Implementations/Redis/Secure/EncryptedRedisPubSubReceiver.cs
- Fixing bug where blocking readers weren't decrypted
- Fixing bug where there wasn't an API to see if the reader was already setup for blocking reads
> Fixing bug where blocking readers weren't decrypted
